# Generated by Django 3.2.12 on 2022-05-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech_app', '0003_auto_20220429_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(max_length=280),
        ),
    ]
